<!-- HTML -->
<div>
    <strong>HINWEIS ZU DEN BILDQUELLEN</strong><br/><br/>
    DIE AUF DIESER WEBSEITE VERWENDETEN BILDER / VIDEOS WURDEN AUS ÖFFENTLICHEN QUELLEN IM INTERNET ENTNOMMEN. WIR BEMÜHEN UNS SICHERZUSTELLEN, DASS ALLE BILDER / VIDEOS LIZENZKONFORM GENUTZT WERDEN. SOLLTE DENNOCH EIN BILD OHNE DIE ERFORDERLICHEN RECHTE VERWENDET WORDEN SEIN, BITTEN WIR UM EINE NACHRICHT, DAMIT WIR DAS BETREFFENDE BILD UMGEHEND ENTFERNEN KÖNNEN.
</div>
    

<!-- STYLE -->
<style>
    div {
        padding: 20px;
        background-color: rgb(5, 32, 43);
        font-style: italic;
        color: rgb(12, 73, 97);
    }
</style>